### ISSUE TITLE
A Perl 5.20 specific issue in zonemaster-engine

### ISSUE THREAD

**Issue by mtoma** [zonemaster/zonemaster-engine#469] opened 2019-01-10 14:31 UTC
The new profiles branch has an issue with some JSON value specific to the version of JSON in Perl 5.20 as can be seen in:
https://travis-ci.org/zonemaster/zonemaster-backend/builds/477783002

Error:  Property resolver.defaults.fallback is of type Boolean at /tmp/local-lib-pZVpnQ/lib/perl5/Zonemaster/Engine/Profile.pm line 225

The same code passes the tests with all other versions of Perl.

In previous tests the same error was showing up for ip_v4 and ip_v6 variables. They were set to 1, setting them to JSON::PP::true fixed the problem.

This is not feasible for the resolver.defaults.fallback variable as it is not used explicitly in the zonemaster-backend.

**Comment by vlevigneron** [comment] 2019-01-11 09:53
I'm not able to reproduce it.
```
> perl -v

This is perl 5, version 20, subversion 3 (v5.20.3) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)
[...]

> perl -I./lib ./t/test_DB_backend.pl PostgreSQL
ok 1 - Testing a supported database backend: PostgreSQL
ok 2 - use Zonemaster::Backend::RPCAPI;
ok 3 - An object of class 'Zonemaster::Backend::RPCAPI' isa 'Zonemaster::Backend::RPCAPI'
[...]
```

**Comment by vlevigneron** [comment] 2019-01-11 11:36
It seems that nobody can reproduce the issue which is still present in Travis. First I'll propose a patch that provide a more detailed output in case of die. It could help to understand what's wrong and what should be changed in the code to deal with that issue.

**Comment by vlevigneron** [comment] 2019-01-15 08:38
The issue should be fixed by https://github.com/zonemaster/zonemaster-engine/pull/472

**Comment by sandoche2k** [comment] 2019-01-17 20:50
@mtoma could be closed ?

**Closed** 2019-01-18 08:06 UTC
