### ISSUE TITLE
Comparing DNSSEC errors with another tool does not result in the same results

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#540] opened 2019-05-04 22:03 UTC
https://dnssec-analyzer.verisignlabs.com/ok.ok.sigexpired.bad-dnssec.wb.sidnlabs.nl
https://zonemaster.net/result/ebe1a2dac06ef2ef

**Comment by vlevigneron** [comment] 2019-10-03 14:35
@sandoche2k Can you elaborate on that ?

**Comment by sandoche2k** [comment] 2019-10-03 14:56
I re-did the test for the domain with zonemaster and dnsviz:
https://zonemaster.net/result/ebe1a2dac06ef2ef 
http://dnsviz.net/d/ok.ok.sigexpired.bad-dnssec.wb.sidnlabs.nl/dnssec/


The chain of trust has errors, but it is not viewed by Zonemaster.

**Comment by vlevigneron** [comment] 2019-10-03 15:21
@sandoche2k right but issues are not in Child or in Parent zone. I guess there is no test case yet that could catch that issue in Zonemaster. Can you confirm ?

**Comment by matsduf** [comment] 2019-10-03 15:58
@sandoche2k, what test case do you think should cover this? I think this would be a new test case. Then the issue should be in the Zonemaster repository for a new test case.

**Comment by matsduf** [comment] 2019-11-13 09:21
F2F: TC and specification to be created in zonemaster/zonemaster.

**Comment by matsduf** [comment] 2022-07-11 13:09
The issue is out of scope of Zonemaster at the present. Zonemaster is focused on the delegation point.

**Closed by matsduf** 2022-07-11 13:09 UTC
Labels: A-TestCase, T-Question
