### ISSUE TITLE
Some nameservers are not resolved from Zonemaster, even though they were accessible

### ISSUE THREAD

**Issue by sandoche2k** [zonemaster/zonemaster-engine#504] opened 2019-03-13 09:27 UTC
https://zonemaster.net/result/b2fe4826d3fc1244

For the domain "myriam-kassem.fr", zonemaster had a nameserver warning saying that NS (ns200.anycast.me/46.105.207.200) for the domain was not accessible. But, when a dig request was made from the ZM VPS, for the same NS, it was resolving. 

The issue was identified by @vlevigneron as an old code has been put in place to evict servers that were not responding.

**Comment by sandoche2k** [comment] 2019-03-13 09:29
Related to the BUG https://github.com/zonemaster/zonemaster-engine/issues/438

**Comment by vlevigneron** [comment] 2019-03-13 09:48
Well, here is what I found out.
We have a blacklisting mechanism that prevents query multiple times servers that do not respond.
The servers ns200.anycast.me/dns200.anycast.me are blacklisted because they answer REFUSED to a '.' query. It's their right.
The issue is that we have the zonemaster/zonemaster-engine#438 BUG that does not make a difference between unreachable and REFUSED responses.

IMHO, we have 3 options :
1/ Fix zonemaster/zonemaster-engine#438. As the problem is perhaps in LDNS and not in zonemaster code, it is not easy to fix in a short term.
2/ Inhibits for the moment blacklisting mechanism. Very easy but could slower processing in case of really broken zones.
3/ Adapt blacklisting mechanism. Did some tests, not sure it will be very effective.

**Comment by sandoche2k** [comment] 2019-03-14 09:45
@vlevigneron remove the blacklisting for now and close the issue. Also, create a new issue to put the blacklisting again.

**Comment by matsduf** [comment] 2019-03-19 08:04
Fixed by #511.

**Closed by matsduf** 2019-03-19 08:04 UTC
Labels: Prio High, bug
